# Generated by Django 2.2.4 on 2020-11-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('-name',)},
        ),
    ]
